### ISSUE TITLE
ml.plots.decomposition does not show contribution of individual stresses anymore

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#119]
The default argument has been changed from split=True to split=False just before releasing the master-version. This has a large influence on graphs I and other people make everyday. It would be nice if these changes were not applied just before a release.

**Comment by raoulcollenteur** [comment]
Sorry for this, I only found this issue just before the release and needed to do something on it as we now use the RechargeModel in the Paper on Pastas. I forgot to add anything in the release notes on this. I would however be in favour to keep the default for the split argument on False for the following reasons.

I explained in  #120 that I think the RechargeModel will not support any split option, and since this is likely to become the basic stress model in the future when adding recharge to the TFN model I think split=False makes sense as a default value.

We could change de default value to split=True but that would mean an error is raised every time somebody will use RechargeModel and plot.decomposition. We could also silently check if split is supported and internally change to split is False for all stress models that do not support split.

Thoughts?

**Comment by rubencalje** [comment]
WellModel supports istress as well. I would be in favour of setting split=True as the default again (and even add the split argument to plots.results as well, but that is for later).

Like you propose in your last sentence, we could add an attribute for each stressmodel, for example called 'nsplit', to determine by how many stresses the contribution can be splitted. Right now this is done explicitly by looking at the length of sm.stress. We can even keep this behaviour if nsplit is not defined. In this way, we only have to change RechargeModel and get_contribution.

When a linear RechargeModel is used, nsplit will be set to 2, and the contribution will be splitted. When a non-lineair RechargeModel is used, nsplit will be set to 1. You can still run ml.plots.decomposition to split the other stressmodels in the model however. That would be a better solution than to set split to False by default.

**Comment by mbakker7** [comment]
+1 for Ruben’s proposal

**Comment by rubencalje** [comment]
I added the nsplit attribute to RechargeModel, and set split to True again.

Raoul, if you want to split the contribution for a lineair RechargeModel, you have to set nsplit to 2 in the __init__ of this class. I do not know how the RechargeModel works or will change in the future exactly.
