### ISSUE TITLE
Change default value of noise model to the mean of the oseries time step

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#124]
I would like to propose to change the default value of the noise model (noise_alpha) the mean/median of the time steps of the oseries. 

Now the default value is 14 (DAYS?). This high value causes the noise model to explain a lot of the variation when high frequency data is used (e.g. 1 day) at the first iteration of the optimisation and troubles the parameter estimation. Changing this value almost always improves parameter estimation in my experience. This change would ensure the initial value is better related to the data.

Possibly the Median time step is actually a better default value, as it will be less skewed by gaps in the data.

Anyone against this?

**Comment by rubencalje** [comment]
ok, the median of the series_original of the oseries then?. But it should not be less than the timestep of the model. So it should be more than 1 day when simulating with a daily frequency, and more than 1/24 days when simulating with an hourly frequency.

**Comment by mbakker7** [comment]
Not sure what is wise here. Why should it be more than 1 day when
simulating with a daily frequency?
I think the mean time step is not a bad idea. That means that the
correlation between two residuals is exp(-1) (that is probably where the 14
days came from to begin with).
But I agree that this value is too high for daily data.

**Comment by rubencalje** [comment]
I mean the starting value should not be lower than 1 day in a daily simulation, because the model only receives daily values during the optimisation, and does not know the data really is more frequent. It should off course be possible to go lower than 1 day during the optimisation.

**Comment by mbakker7** [comment]
Maybe I don't quite get it. Do you mean the case that you have hourly data
but you are calibrating on daily data? I agree that the starting value
should be a function of the (median or mean) time step of the calibration
data (oseries_calib).

**Comment by raoulcollenteur** [comment]
Just submitted a commit to address this issue. The initial value for Noise alpha is now calculated as the median value of the `oseries` time steps at the time when the stressmodel is added. It seems to work well for all examples.

Just one remark:
if a different period is chosen for solving (e.g., where larger time steps are present) the initial value is not changed. This is however no different then it was and the user needs to change the initial value manually. This is hard to do automatically each time when solving because we would need to check if the user changed the initial value of alpha....

**Comment by mbakker7** [comment]
I thought we have an 'initialize' keyword option?
What we could do is always initialize unless the 'initialize' keyword
option is set to False.
Would that work?

**Comment by rubencalje** [comment]
> Just submitted a commit to address this issue. The initial value for Noise alpha is now calculated as **the median value of the `oseries` time steps** at the time when the stressmodel is added. It seems to work well for all examples.
> 
> Just one remark:
> if a different period is chosen for solving (e.g., where larger time steps are present) the initial value is not changed. This is however no different then it was and the user needs to change the initial value manually. This is hard to do automatically each time when solving because we would need to check if the user changed the initial value of alpha....

This change gives problems when solving a model with a daily frequency, where the series_original has an hourly frequency (as I already predicted). The initial_value of noise_alpha is then 1/24 (0.042) day. The solver is unable to find the right noise_alpha. The objective function is insensitive to any change of noise_alpha around 0.042, because the data that the model is calibrated on has a timestep of 1 days.

**Comment by raoulcollenteur** [comment]
Manually changing the initial value of alpha you can find an optimum for noise_alpha with hourly data?

I would expect the noise model / time series frequency itself is troubling and not the parameter value. There is probably a lot of autocorrelation right?

**Comment by rubencalje** [comment]
> Manually changing the initial value of alpha you can find an optimum for noise_alpha with hourly data?

Yes, when we (I mean David) set the initial value to 14 days, we get an optimal value for noise_alpha of 20 days.

The small initial value for noise_alpha effectively turns the noise model off. The optimal value of noise_alpha generally goes to 0 and the standard deviation of noise_alpha is NaN.

**Comment by rubencalje** [comment]
I would be in favor of setting the initial value of noise_alpha back to 14 days, or lower it to 7 days.

I see no reason why the noise_alpha should be lower just because the frequency of the measurements are higher. The noisemodel already takes the measurement interval into account.

**Comment by dbrakenhoff** [comment]
As @rubencalje indicated, this new behavior doesn't work well when solving highly frequent series on a different frequency, i.e. my data is hourly, but I want to solve on a frequency of 7 days. The noise_alpha is set based on the original timeseries (hourly) which results in a small value. When optimizing I have seen the noise_alpha going to 0, effectively turning itself off. Setting a different initial value for noise_alpha then yields a completely different result (in which the noise model has not turned itself off). 

In my opinion, it's annoying to have to manually set the noise_alpha based on the frequency I want to solve with to override this default setting. Since by default the model frequency is daily, shouldn't noise_alpha reflect that setting, and not whatever the original series came in as? When you want to solve with a different frequency, you have to do that manually. At that stage it would make sense to me to also alter the noise_alpha initial value.

Thoughts?

**Comment by dbrakenhoff** [comment]
Proposed change in #164

**Comment by raoulcollenteur** [comment]
Closing this issue
