### ISSUE TITLE
Making values from ml.settings default when nothing is provided for solve?

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#141]
@OnnoEbbens proposed to use the tmin and tmax stored in the settings dict when no values for these arguments are provided in the solve method (see PR #140). This would change the default behaviour we have right now, which is to derive it from the data.

This would allow manual settings of the settings dict. Doing that bypasses any built-in checks and causes (weird) errors downstream, so I in my opinion this should be discouraged. We could support this, but then I think we need to subclass the dict class and create a enhanced settings dictionary with specific set_methods.

This is a lot of work and the benefit is minimal I think. Setting the settings through solve arguments should remain the way it is done.

**Comment by dbrakenhoff** [comment]
I see your point about not modifying ml.settings directly. But consider this example:

We currently have a project in which
- We have data from an online source we do not control, so we store our modifications (i.e. removing certain periods) elsewhere. This is done by storing the observations series name and the tmin/tmax and removed periods in a different table. 
- We save the pastas models without timeseries, as it needs to be possible to update the timeseries in models if the user so desires. When the models are loaded, the timeseries are looked up in a pastas.Project. 
- When we run our analysis, we load the models, using either the old or updated timeseries, and if necessary optimize the models. In this situation it's nice to have all your custom settings applied to the model immediately, without having to think about passing stuff to each ml.solve().

I guess a solution would be to modify pr.solve_models() to accept tmin and tmax arguments that contain the tmin/tmax per model. 

Still would be nice to have the option of "saving" your customized tmin/tmax/settings with your model instead of having to provide them to the model each time you want to optimize.

(Perhaps this question is something we can discuss at a developer's meeting...)

**Comment by raoulcollenteur** [comment]
> I guess a solution would be to modify pr.solve_models() to accept tmin and tmax arguments that contain the tmin/tmax per model.

this method already takes tmin and max through the kwargs, so this should be possible right?

**Comment by dbrakenhoff** [comment]
I think this can be closed?
