### ISSUE TITLE
first entry in ml.noise() is set to 0

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#152]
I came across the following result as I was optimizing my timeseries models:

![bad_fit](https://user-images.githubusercontent.com/6552225/65669769-6ea1b480-e044-11e9-8408-16c8038c3169.png)

This occurs because the first entry of the noise calculation is set to 0 in the code on line 153 (in combination with a large `noise_alpha`):
https://github.com/pastas/pastas/blob/21a8464f4fc1b47cc67af9108cefc6069e146df4/pastas/noisemodels.py#L148-L155

This first value of the noise (before changing it to 0) is equal to that ca. 2m offset between the model simulation and the observations. Commenting out this line ensures that value of `constant_d` is such that the model is on top of the observations.

My question therefore is if this setting the first value of the noise to 0.0 is the correct way to go? Would removing that line cause any problems in other situations?

**Comment by rubencalje** [comment]
We used to set the first value of the noise to 0, because we used the multiply method, and had to assign a fill-value. Now that Raoul has optimized the code, the line 'res.iloc[0] = 0 ' takes the form of the fill_value.

I think we can (and should) remove this line, so that the first value of the noise is equal to the first value of the residuals. In this way, all of the model error is taken into account during the optimization. I think this solves a small part of the problem we have with bad fits using a noisemodel.

**Comment by raoulcollenteur** [comment]
Good point. I actually only put in that line to ensure I didn't change the outcome compared to the old code.

Leaving the residual values for the first time step might be an idea, although that also means the beginning of the simulation becomes very important. I thought @mbakker7 had some thoughts on a good first value for the noise?

**Comment by rubencalje** [comment]
I think we should address this before the next release. therefore I made a pull request: #163

**Comment by raoulcollenteur** [comment]
I think we should not change anything to the current noise model with regard to this. I think the noise model works fine as is, and where it does not work either 1) the noise model is not appropriate and another noise models is needed (e.g., second-order) or 2) the model structure is inappropriate (as is like in the example given by @dbrakenhoff here).

Just to be clear from my experience, I actually never see the problem above anymore once I change the model structure or gwl observation frequency. To me this strongly suggests that the problem lies elsewhere. I suggest we work on new noise models instead of making ad hoc changes, such as the one proposed by @rubencalje in PR #163. As suggested in the PR discussion, this could become a new noise model we can test.

We could then change the default noise model in the future once we agree on a "better" noise model.

**Comment by rubencalje** [comment]
But wouldn't it be nice if you did not have to change your model structure or gwl observation frequency to fix this? I do not see why we cannot fine-tune the current noisemodel, like we do with the rest of pastas.

**Comment by raoulcollenteur** [comment]
I think the main reason is that this implements the current state of science and is referenced. I totally agree of course it would be nice to have better noise models, but this will still take some research.

**Comment by raoulcollenteur** [comment]
A while ago, but the following links might be interesting for this issue: 

- https://en.wikipedia.org/wiki/Cochrane–Orcutt_estimation
- https://en.wikipedia.org/wiki/Prais–Winsten_estimation

Prais-Winsten suggest the first value should be weighed by:

```
rho = np.exp(-delt / alpha)
w = np.sqrt(1-rho**2) 
```

Not sure what delt would be, maybe the mean timestep ?

**Comment by EitvanderMeulen** [comment]
Pastas Issue #152
The noise_alpha is 4952.12 (very large) in the model of DBrakenhoff, this means that parameter phi=exp(-1/4952.12)=0.9998, almost 1. This means almost a unit-root problem or random walk model, a non-stationary model. Probably if there was a noise-parameter instead of an exponential term in the Pastas model it would be a unit-root problem (see web page: [‘hoogfrequente tijdreeksmodellering'](https://www.amo-nl.com/hoogfrequente-tijdreeksmodellering/)). Normally such a model cannot be used for interpretation of the hydrological system or making predictions. Change your model structure or try to model without a noise model or try to model on a higher time basis (weeks, two-weeks, …) and apply a verification of the model. 

**Figure1: Result modelling without a noise model**
![image](https://user-images.githubusercontent.com/49031217/84859891-4fcdcd00-b06e-11ea-9370-5715d2a49d60.png)

**Figure2: Results verification**
![image](https://user-images.githubusercontent.com/49031217/84859957-755ad680-b06e-11ea-8233-f48770c72ba5.png)
![image](https://user-images.githubusercontent.com/49031217/84859997-886da680-b06e-11ea-9551-39801d7d27be.png)

**Table 1: Diagnostics of residuals without noise model**

Test of   residuals | Test   (confidence) | Result | Detail
-- | -- | -- | --
D'Agostino-K2 | normality (99%) | No | p=0.00
Shapiro-Wilk | normality (99%) | No | p=0.00
Portmanteau | no autocorr.   (95%) | No | 22339.16>25.00
Runs | no autocorr.   (95%) | No | p=0.00
Engle | homosced.    (95%) | No | p=0.00

There is autocorrelation (Portmanteau: 22339.16>25.00)
Advice: extend your noise model or aggregate your dataset to a lower frequency

The modelling without a noise model gives a better fit than the modelling with a noise model. This is a strange result, a noise model should be helpful to reduce autocorrelation. Is the optimization method implemented in Pastas for models with a noise model optimal?

Table 1 shows that the model used is not approved. But it is unlikely that a lower frequency of modelling will give models with good diagnostics. There must be explanation for the trend in the residuals. A solution can lie in the understanding of the hydrological situation and to extend the model with the right explaining input variables.

**Comment by raoulcollenteur** [comment]
After @mbakker7 latest commit updating the noisemodel this issue is now closed. First value is the residual and the weight is almost one resulting from a high value for dt. The new noise model will change calibration results (generally for the better) and this change is documented in the release notes.
