### ISSUE TITLE
parameters polder function

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#156]
As far as I know, the polder function is still experimental and needs some work. 
Three issues:
1. Right now, the parameters are chosen as x/(2*lab) and 1/cS. I am not sure that is the most logical, although it gives the most obvious link with aquifer parameters. Anybody against experimenting a bit with these?
2. Right now, there is no scaling factor. I understand why: in a semi-infinite aquifer, the ultimate rise is a function of the rise in the river and the aquifer parameters. But this function is intended to be used as well in other situations, for example finite aquifers. So I suggest to add a scale factor, like the other response functions.
3. I will implement a conservative (but quick) estimate of tmax.

**Comment by rubencalje** [comment]
The idea about the current implementation of the Polder Function (instead of Gamma for example) is that you can get some properties of the system. It then helps if there are less parameters.

I changed the Polder function from 3 to 2 parameters, also because I got an email from Wilbert Berendrecht, that he had problems with the scaling factor: the parameters were too correlated. I never really used the Polder function however (because of point 3), so I cannot say it is ok the way it is now, and so I am not against experimenting. Maybe we can add the scaling factor optionally?

**Comment by mbakker7** [comment]
Ruben,

I think the scaling factor should be in there. For one thing, this function
should work for general settings, not just for a semi-infinite aquifer. I
understand what you are saying, that the parameters are highly correlated
(which may be true) and if you want to get physical parameters out then it
is preferred to fix the scaling factor to 1. My suggestion is to add the
scaling factor, but, for now, fix it to 1.

Mark

**Comment by rubencalje** [comment]
Hi Mark,

The calculation for tmax seems to work well, as is fixing of the scaling factor to 1 (by default the scaling factor is now not fixed by the way).

The initial value of the 'b'-parameter is set to 0.1 (like it always has been). This causes a very slow response, see [this graph from the docs](https://pastas.readthedocs.io/en/latest/_images/examples_003_response_functions.ipynb_3_0.png) for example. With the initial parameters, there is allmost no influence from my varying river level, and the optimisation is unable to find an influence I am pretty sure exists. Therefore I think we should set the initial value of this parameter to 1.

Another problem arises then. The tmax-value is getting so big, that the entire memory of my computer is used to generate a step-response, after which everything freezes. I think we can solve this in 2 ways: limit the lower bounds for the parameters (for example by a=0.001 and b=0.001). A better and more robust approach probably is to let t not get any larger than the length of the series we are convoluting. This will also work for other response-functions (Edelman has the same problem).

**Comment by mbakker7** [comment]
Ruben,

I fixed A in my latest commit.

The bounds and initial values of b are interesting and important.
As it stands now, b = 1 / sqrt(cS). So for a resistance of 1000 days and a
storage coefficient of 0.001, the value of b=1, which seems reasonable. So
setting it to 1 is fine with me and I commited that.

A tmax larger then the length of the series does, obviously, not make any
sense. We need to fix that in the code, but I am not sure where a good
place would be. And do we set it then to length(observations) + warmup? How
do we pass that value to the rfunc so it has access to that value?
Suggestion?

Mark

**Comment by rubencalje** [comment]
I think we should limit the tmax by the length (in days) of the simulation index, so normally this would be the length of the observations + warmup. We can pass this from the model, to the stressmodel to rfunc, just like we do with dt. This is not the prettiest, but I do not see any alternative. I can change it if you agree.

This issue is linked with issue #132 by the way.

**Comment by rubencalje** [comment]
dt in this case is a float: the timestep of the simulation in days. So for a daily simulation it is 1. and for an hourly simulation it is 0.042. So it is useless to sum this value.

**Comment by mbakker7** [comment]
You are right. So we have to pas maxtmax. Unless you know a better name.
You want to try to do this? Still don’t feel great about it, as it is a lot
of passing around.

**Comment by raoulcollenteur** [comment]
@mbakker7 can we close this issue as well now?

**Comment by mbakker7** [comment]
If maxtmax is now implemented in the computation of tmax for all response functions, this issue can be closed.
