### ISSUE TITLE
Uncertainty band in plot

### ISSUE THREAD

**Issue by thijshdsr** [pastas/pastas#165]
Is there a way to come up with an uncertainty based on a PASTAS model calculation? This in order to create figures like these:
![afbeelding](https://user-images.githubusercontent.com/44226946/68124358-7c820980-ff0f-11e9-8e8f-54e5c676b032.png)

I took a look at the docs however I don't know if it's not possible or I'm just not looking hard enough.

**Comment by raoulcollenteur** [comment]
Hi Thijs. We are currently working on this feature and have an outstanding Pull Request (PR) to add this functionality into the development version (dev-branch) and to the stable version (master branch). I expect this PR to be merged this week and later this month to the stable version with the next release (which is a little overdue but coming soon).

If you can't wait, feel free to test it from the uncertainty branch :) We will wait one more release to add documentation and examples to Pastas because we want to test it as little more before we start promoting it. However, the code should include docstring and example_uncertainty.py should get you on your way.
