### ISSUE TITLE
Provide instances instead of classes for response functions 

### ISSUE THREAD

**Issue by rubencalje** [pastas/pastas#360]
Right now we pass a rfunc class to a stressmodel. In this way, we cannot add optional arguments to a response function. For some stressmodels, like Spline or Kraijenhoff, extra optional arguments are possible.

Therefore I propose we change the rfunc argument in a StressModel from an rfunc-class to a rfunc instance. To keep existing code working, an rfunc-class will be permitted for now as well. We will make an instance of the class  in the init of the stressmodel in that case.

Also these extra arguments need to be saved to a pas-file. We can use the same procedure as is implemented for recharge-models, see pull request #359.

**Comment by rubencalje** [comment]
Implemented by pull request #361

**Comment by raoulcollenteur** [comment]
Reopening this issue to complete the change over Pastas 0.23 and 1.0.

- [x] Add warnings when users use classes instead of errors for rfuncs in Pastas 0.22
- [ ] Throw Errors when users use classes instead of errors for rfuncs in Pastas 0.23
- [ ] Update all example materials to use rfunc instances in Pastas 0.23
- [ ] Remove error messages for Pastas 1.0.

 Please do not start making these changes in the Dev-branch before PR #455 is merged, otherwise this would be chaos.

**Comment by raoulcollenteur** [comment]
After merging  #466 the only thing left to do is to remove the warnings for Pastas 1.0. Updated the milestone accordingly.

**Comment by raoulcollenteur** [comment]
Closing after merging https://github.com/pastas/pastas/pull/504
