### ISSUE TITLE
[ENHANCEMENT] Implement Type Hints into Pastas

### ISSUE THREAD

**Issue by raoulcollenteur** [pastas/pastas#389]
**Describe the proposed enhancement**
Following Pastastore, implement Type Hinting into Pastas to improve Error feedback. @dbrakenhoff, good idea?

**Comment by dbrakenhoff** [comment]
I think it's a "nice-to-have" addition for users. As far as I know, they're just hints that can generally also be picked up by users from the docstring. So not sure how error feedback would improve? But it does allow you to check the code with mypy (which I haven't really looked at much) and I think the hints can be pretty helpful.

**Comment by OnnoEbbens** [comment]
I thought you could also enforce the types but now that I look into it I see that's not true.

This issue came up when someone tried to use the `ps.plots.series` function with a DataFrame instead of a Series. From the error it was hard to know what went wrong. We could manually add type checks like this :
```
if not isinstance(head, [pd.Series, ps.Timeseries]):
    raise TypeError('expected pandas Series or pastas Timeseries object')
```
But this is maybe a bit to rigid for pastas. Besides it is a lot of work to implement this for the relevant pastas functions.

**Comment by martinvonk** [comment]
It would be nice to have one big file with the correct types of each arguments. This way these types can be implemented correctly in functions. Additionaly, checks can be implemented to force the correct types.
