### ISSUE TITLE
Multiple INFO warnings about replacement of nans in stresses

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#510]
Nan values are automatically filled in version `1.0.0b0`. The `recharge` series in notebook "A Basic Model" has nan values. When a stressmodel is built with the `recharge` series as stress, the `INFO` statement is printed to the screen twice. In the next code block, where the model is solved, the `INFO` statement is printed yet again.

Desired behavior: One `INFO` statement upon creation of the `StressModel` and none after that.

**Comment by raoulcollenteur** [comment]
Closing issue after merging PR #520

**Comment by mbakker7** [comment]
The double printing of the INFO statement is gone when creating the `StressModel`. Thanks!

What `pastas` still does is print an INFO statement upon creation of the `StressModel` and then again when the `Model` is solved. Then is still double work and a double INFO statement. It seems that in `Model.solve`, no use is made of the series where the nans are already filled.

**Comment by raoulcollenteur** [comment]
In previous versions this info message was not reported, because the validate_series method filled up the nans. That behaviour however, caused a real bug (not just a small overhead like now), because the changing the fill_nan setting actually had no impact anymore. To see this, run the following code with an old version of Pastas.

```
index = pd.date_range("2000-01-01", "2000-01-10", freq="D")
series = pd.Series(range(10), index=index)
series.loc["2000-01-05"] = pd.NA
ts = ps.timeseries.TimeSeries(series)  # Default is interpolate
ts.series
```

and then:

```
ts.update_series(fill_nan="mean")
ts.series
```

You fill see that nothing changed, while it should have (4.55 as fill value).

With the new code, if you update the fill_nan setting, like any other setting, it is actually used (try code above with new pastas version). This extra overhead is I think the price to pay for not providing time series without nans or using series.fillna(0.0) from the start.

To deal with this we would need to add lots of complexity to the TimeSeries object again, which would cause overhead even if people provide a gap-filled time series, so I'd prefer to only punish those who don't provide gap-filled time series. What could perhaps be done is a global variable to check if the fill_nan is already reported and otherwise silent them.

**Comment by dbrakenhoff** [comment]
Wont fix.
