### ISSUE TITLE
[ENHANCEMENT] Use solver instance for different models

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastas#511]
**Describe the proposed enhancement**
Currently it is not possible to use one solver instance for multiple models. A new instance of the solver has to be created for each model. However, I don't think this behavior is consistent since it is not necessary for e.g. response function instances.

The difference is that the model is an attribute of the solver class. However, we could achieve the desired behaviour by reinitializing/resetting the solver class every time when a new model is added to the solver (by calling `solver.__init__`?).

**Expected behavior**
Currently we have to do:
```
rfunc = ps.Kraijenhoff()
for head in observations:
    ml = ps.Model(head)
    ml.add_stressmodel(ps.StressModel(stress, rfunc=rfunc))
    solver = ps.LeastSquares()
    ml.solve(solver=solver)
```

But I'd like to be able to do:
```
rfunc = ps.Kraijenhoff()
solver = ps.LeastSquares()
for head in observations:
    ml = ps.Model(head)
    ml.add_stressmodel(ps.StressModel(stress, rfunc=rfunc))
    ml.solve(solver=solver)
```

**Comment by raoulcollenteur** [comment]
And what would be the advantage of doing that? Except not making a new solver instance? Seems to me that we would have to add code complexity with no clear gains ..  

For consistency, you should also not re-use a stressmodel instance for example, because ml.set_parameters updates sm.parameters. So perhaps it would be better to not re-use any instance anywhere, that would also be consistent and prevent some strange behaviour when reusing instances.
