### ISSUE TITLE
[BUG] naming of parameters in the `DoubleExponential` rfunc

### ISSUE THREAD

**Issue by mbakker7** [pastas/pastas#527]
In the `DoubleExponential` function, the parameters are called a, b, and f in the impulse response function and a1, a2 and alpha in the naming of the parameters. It makes some sense to call them a1 and a2. I can live with alpha. But that means the impulse response need to be updated. How to get at a_1 and a_2 in latexify? This is in the pastas_docs_1.0 branch.

**Comment by martinvonk** [comment]
This okay with you? If so, feel free to close.

since commit [e1e7ceb], `pastas.DoubleExponential.impulse` yields: (https://github.com/pastas/pastas/pull/502/commits/e1e7ceba86f23251a884ae8f6d03dfb8043a0cea):
![image](https://user-images.githubusercontent.com/66305055/216610697-788e4bc0-a730-422c-b961-7bc5f5e1bff0.png)

**Comment by mbakker7** [comment]
looks great. thanks.
