### ISSUE TITLE
model with simulation time step freq="H"

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastas#93]
A pastas Model is initialized with a hard-coded daily frequency. This makes pastas resample my hourly stresses to daily values when creating the model. Then when I solve on an hourly frequency, pastas uses the original hourly series to eventually solve the model. The downsampling step is quite unnecessary in this case so how can I force pastas to skip it?

One solution would be to allow Models to be initialized with a frequency. But this probably adds to the (or just my) confusion about pastas settings. 

This might lead to a whole other discussion, but currently there are three levels (that i can think of now) at which settings can be provided in pastas:
- Timeseries settings, these define resampling/filling/extending logic for timeseries.
- Stressmodel settings, these should be derived from Timeseries settings. (not sure what happens when they're provided to Stressmodel).
- Model settings: hard-coded at creation, but can be changed when solve() is called with kwargs or by directly editing `ml.settings`.

I've heard there was a reason to not include a settings kwarg in Model(), but in my case, I wouldn't mind if the option existed... So what would be the best way to avoid pastas doing extra resampling work? I'm curious to hear your thoughts!

**Comment by raoulcollenteur** [comment]
Short answer regarding your question, you can update the model frequency after model creation, e.g:

`ml.settings["freq"] = "H"`

The following line in the model `add_stressmodel` method is causing the problem:

`stressmodel.update_stress(freq=self.settings["freq"])`

Since this is also done in the `initialize` method I think we can remove it here, but that would mean the `simulate` and related methods would not work anymore until the model is solved. I can see the benefit of removing this line though and changing something in the simulation methods to check for this when a model is not solved.

> This might lead to a whole other discussion, but currently there are three levels (that i can think of now) at which settings can be provided in pastas:

The problem/challenge is that there are many settings for each time series model:

- The TimeSeries settings: dealing exclusively with the stresses and oseries. For al the TimeSeries they can be set when creating a TimeSeries instance. You then feed TimeSeries objects into the Model and Stressmodels, this gives the most control. Setting TimeSeries settings when creating a stressmodel is just for convenience, they are passed on to the TimeSeries object.
- The Model settings are something different and determine what happens when a model.
- To change to settings of the oseries is rather difficult I think. We could add a method to do this.

> I've heard there was a reason to not include a settings kwarg in Model(), but in my case, I wouldn't mind if the option existed... So what would be the best way to avoid pastas doing extra resampling work? I'm curious to hear your thoughts!

I think we decided to remove the settings from the Model instantiation method to make things less confusing. I was not clear whether or not the settings were applied to the oseries or the model settings. For now I would suggest to stick with the current arguments and change model settings after model creation as suggested above.

**Comment by dbrakenhoff** [comment]
Thanks for the explanation. That works. I wonder whether directly editing `ml.settings` is intuitive or not. I guess it is once you know it exists. I just didn't realize before I started looking that these settings were hard-coded. 

For what it's worth, one way of making clear model settings belong to a model could be to just call it `modelsettings` and using the docstring to explain what these settings do (which was probably the situation before it was changed)? The challenge remains of course to help the user know which settings are available. So maybe directly accessing ml.settings is a good approach after all.

**Comment by mbakker7** [comment]
We really need to change this, as it is very unintuitive. Maybe after we have settled on the new approach to set the frequency of the model (which was just implemented), we can revisit this issue.

**Comment by rubencalje** [comment]
Like Davíd suggest, I think we should add the frequency as an optional argument to the __init__ of the Model class (still with the default value days ('D')).

This is more intuitive than to change the settings-dictionary.

**Comment by raoulcollenteur** [comment]
I think what we decided upon a (long) while ago is to not provide a frequency for simulation and let Pastas find out the lowest frequency for simulation. Then, if a user wants to change to frequency this is done through the solve method.

The method ml._set_freq is not used yet but was meant to figure out the frequency of a stressmodel and change the model frequency if it is lower then the current frequency. However, as the frequency is now set to "D" when initiating the model this method is not called.

We could alternatively go with a default value, and delete the set_freq method altogether. This is the easier option, but requires the modeller to know what he is doing more.

**Comment by dbrakenhoff** [comment]
+1 for the option to add `freq="D"` to `ps.Model` and set the default to "D". 

The default values means the behavior is the same as it is now and it's more explicit. Letting pastas find the lowest frequency sounds fancy, but not something we do now and that still doesn't give the user much control.

**Comment by raoulcollenteur** [comment]
+1 for the option to add freq="D" to ps.Model and set the default to "D".

 and we can then remove ml._set_freq()

**Comment by dbrakenhoff** [comment]
Should we addres this issue for next release as well?

**Comment by raoulcollenteur** [comment]
Yes, I'll implement it later this week!
